name: cadence_coach
description: Cadence Coach with BLE and vibration alerts
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^2.0.2
  vibration: ^1.7.4

  # Compatible versions for Codemagic iOS build
  geolocator: ^14.0.1        # <- downgrade to avoid conflict with package_info_plus
  package_info_plus: ^8.3.1  # <- matches geolocator_linux dependency
  path_provider: ^2.1.5       # <- safe for iOS 13+
  csv: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
