workflows:
  ios-clean-build:
    name: iOS Clean Build for flutter_application_1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Pull latest code
        script: git pull origin main

      - name: Flutter clean
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/Flutter/Flutter.framework

      - name: Get Flutter packages
        script: flutter pub get
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
