workflows:
  ios-build-v56:
    name: iOS IPA Build v1.0.56+56
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean
      - name: Build iOS IPA
        script: |
          flutter build ipa -t lib/main.dart --export-options-plist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: CAM9PCSW27
          issuer_id: <YOUR_ISSUER_ID>
          private_key: Encrypted: ...
        submit_to_testflight: true
        distribute_to_beta_testers: true
