workflows:
  ios-deploy:
    name: iOS Build & Deploy v1.0.48
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: stable
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS Release
        script: |
          flutter build ios --release --no-codesign
      - name: Archive & Export
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive archive
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/build/Runner
    artifacts:
      - build/Runner/Runner.ipa
    publishing:
      app_store_connect:
        api_key: Encrypted(${APP_STORE_CONNECT_API_KEY})
        ipa_path: build/Runner/Runner.ipa
        notify_testers: true
