workflows:
  ios-workflow:
    name: iOS BLE Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_BUILD_MODE: release
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter packages
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --export-options-plist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your_email@example.com
        on_success: always
        on_failure: always
