name: cadence_coach
description: A cadence optimizer and workout tracker app.
version: 1.0.0+25

environment:
  sdk: '^3.10.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0
  flutter_blue_plus: ^1.15.0
  geolocator: ^12.0.0
  path_provider: ^2.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
