workflows:
  ios-workflow:
    name: iOS Build
    environment:
      vars:
        APP_IDENTIFIER: GoldilocksAI
        APPLE_ISSUER_ID: 9a5a245e-98aa-4eb2-8b80-866b48d1d4ad
        APPLE_KEY_ID: CAM9PCSW27
        CERTIFICATE_PATH: /path/to/AuthKey_CAM9PCSW27.p8
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
    publishing:
      app_store_connect:
        apple_id: kornaus@hotmail.com
        team_id: <your_team_id>
