workflows:
  build_and_deploy:
    name: v1.0.50+50 BLE optimizer
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_NAME: "1.0.50"
        FLUTTER_BUILD_NUMBER: "50"
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Run analyzer
        script: flutter analyze
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Build Android
        script: flutter build apk --release
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      app_store_connect:
        api_key:
          secure: EncryptedKeyHere
        bundle_id: com.example.flutter_application_1
        release_notes: "v1.0.50+50 BLE optimizer live"
      google_play:
        service_account_credentials:
          secure: EncryptedGoogleServiceKeyHere
        track: production
